// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwJmMfTLYU5lAsJsxe5tULpxK1VYLH-UQ',
    appId: '1:695046041251:android:46499ba42b94d09da4d916',
    messagingSenderId: '695046041251',
    projectId: 'running-shoes-app',
    storageBucket: 'running-shoes-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnIpW5IZZnldddLYo1yJyxJOnPJ_A_Pvc',
    appId: '1:695046041251:ios:c733d60c4067ae0aa4d916',
    messagingSenderId: '695046041251',
    projectId: 'running-shoes-app',
    storageBucket: 'running-shoes-app.firebasestorage.app',
    androidClientId: '695046041251-qf08vl8v14tkq7gnjvsrm784hhjalck0.apps.googleusercontent.com',
    iosClientId: '695046041251-fm8qif75ujejnhbgbpdgtlr2i1h215k3.apps.googleusercontent.com',
    iosBundleId: 'com.example.recycleApp',
  );
}
